### ISSUE TITLE
features I'd like to see

### ISSUE THREAD

**Issue by dominikwilkowski** [alex-page/lognana#1]
Hey

It would be great to have some of those things in the future of `lognana`:

- a filter so that verbose can be filtered somehow to be more specific to what you're trying to debug. Maybe a regex or each verbose call having a category associated with it?
- proper ASCII line breaks so that when your message runs over the width limit of your terminal screen it is indented properly again to make reading easier between different calls...
so from:
```
 🔔         INFO:    a lot of text that
breaks into a new line
```
to:
```
 🔔         INFO:    a lot of text that
                     breaks into a new
                     line
```
- proper timestamps and a method to filter by those
- a way to mark certain values with a different color to make them easier to scan-read

**Comment by alex-page** [comment]
Wow - didn't even think of these!

Such awesome suggestions I'll definitely look into adding these ASAP

**Comment by alex-page** [comment]
@dominikwilkowski thanks for the awesome features 👍 

How would you imagine the filtering for timestamps and verbose to work? It will only do the log if certain criteria are met, or searching the list of logs after they are completed?

What is a proper timestamp in your eyes? I understand that the current ones are pretty rough. It could be as simple as the current time `07:00:31` or it could be more advanced like `2016-10-08 00:47:25`. Maybe an option can be provided for the different options and there is a default one.

**Comment by alex-page** [comment]
The new line code would need to calculate the terminal size and then indent based on that. This would not be simple thing to do without dependencies and I am trying to keep this package as lean as possibble. Any thoughts @dominikwilkowski
